{
 "title": "Temperature",
 "description": "BME280 Metrics - by @fronbasal.",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Temperature",
   "type": "graph",
   "description": "Temperature of my room",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "celsius", "label": "Temperature" }
   ],
   "targets": [
    { "expr": "bme280_temperature", "legendFormat": "{{ instance }}" }
   ]
  },
  {
   "title": "Pressure",
   "type": "graph",
   "description": "Pressure",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "pressurehpa" }
   ],
   "targets": [
    { "expr": "bme280_pressure", "legendFormat": "{{ instance }}" }
   ]
  },
  {
   "title": "Humidity",
   "type": "graph",
   "description": "Displays humidity",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "humidity" }
   ],
   "targets": [
    { "expr": "bme280_humidity", "legendFormat": "{{ instance }}" }
   ]
  },
  {
   "title": "Volume",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    { "expr": "loudness*20", "legendFormat": "{{ instance }}" }
   ]
  },
  {
   "title": "Network throughput",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "Mbits" }
   ],
   "targets": [
    {
     "expr": "node_network_transmit_bytes{device=\"eth0\"}*0.000001",
     "legendFormat": "{{ device }}"
    }
   ]
  },
  {
   "title": "Load",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    { "expr": "node_load5", "legendFormat": "{{ instance }}" }
   ]
  },
  {
   "title": "Free RAM",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 26 },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    { "expr": "node_memory_MemFree*0.000001" }
   ]
  }
 ]
}